# src/comparative/configs/train/gpu.yaml
_target_: pytorch_lightning.Trainer

accelerator: gpu
devices: 1
max_epochs: 15
log_every_n_steps: 5
default_root_dir: D:/COmparative_Study_of_Multimodal_Represenations/src/comparative/checkpoints/
