# src/comparative/configs/model/classical_early.yaml

_target_: comparative.models.classical.early_fusion.EarlyFusionClassifier

model_name: distilbert-base-uncased
n_classes: 20   # unique genres, 138 fashion
fusion_hidden: 256
lr: 2.0e-5
wd: 0.01

image_emb_dim: null    # <-- MovieLens no imgs
graph_emb_dim: null
tabular_dim: null
