_target_: comparative.models.vae.hybrid_mvae.HybridMVAE

text_model: distilbert-base-uncased
max_text_length: 64

use_image_cnn: true
image_model: resnet18
freeze_image_cnn: true

graph_emb_dim: 50
graph_hidden: 128

z_dim: 128
classifier_hidden: 256
n_classes: 500

lr: 2e-4
wd: 1e-5
kl_weight: 0.01
