_target_: comparative.models.transformers.vilbert_module.ViLBERTStyleModule
text_encoder_name: distilbert-base-uncased
vision_encoder_name: google/vit-base-patch16-224
num_labels: 139
multilabel: true
freeze_backbones: true
num_xattn: 2
lr: 3e-5
weight_decay: 0.01

# movielens (didn't run)